export enum HabitActionTypes {
    UPDATE_LOG = 'UPDATE_LOG',
    DELETE_HABIT = 'DELETE_HABIT',
    ADD_HABIT = 'ADD_HABIT',
    SELECT_HABIT = 'SELECT_HABIT',
    UPDATE_HABIT = 'UPDATE_HABIT',
    LOAD_HABITS = 'LOAD_HABITS',
    CHECK_HABIT = 'CHECK_HABIT',
    LOAD_LOG = 'LOAD_LOG',
    LOAD_LAST_CHECK_LOG = 'LOAD_LAST_CHECK_LOG',
    SWAP_HABITS = 'SWAP_HABITS',
}

export enum ApplicationStateTypes {
    CHANGE_MODAL_STATE= 'CHANGE_MODAL_STATE',
    LOGIN_STATE= 'LOGIN_STATE',
}
